apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: http://krmp-d2hub-idock.9rum.cc/dev-test/repo_a09fba91af9f # redis 이미지
        ports:
        - containerPort: 6379
        env:
          - name: REDIS_PW
            value: "mooyaho"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379